# Uncomment to enable encoder
# CONFIG_EC11=y
# CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Uncomment the following line to enable the Lily58 OLED Display
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y 

#raw HID
CONFIG_NICE_OLED_WIDGET_RAW_HID_DRIVER=n

#other widgets
CONFIG_NICE_OLED_WIDGET_LAYER=n
CONFIG_NICE_OLED_WIDGET_PROFILE=n
CONFIG_NICE_OLED_WIDGET_MODIFIERS_INDICATORS=n

# Main screen: bongo cat + WPM graph
CONFIG_NICE_OLED_WIDGET_WPM_BONGO_CAT=y
CONFIG_NICE_OLED_WIDGET_RESPONSIVE_BONGO_CAT_CUSTOM_X=0
CONFIG_NICE_OLED_WIDGET_WPM_GRAPH=y

#peripheral
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_CAT=n
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_SMART_BATTERY=n
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_HEAD=y

CONFIG_NICE_OLED_WIDGET_BATTERY=n
CONFIG_NICE_OLED_WIDGET_OUTPUT=n

# Enable ZMK Studio Support
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
 